# Generated by Django 2.1.3 on 2018-12-04 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=30)),
                ('apPaterno', models.CharField(max_length=20)),
                ('apMaterno', models.CharField(max_length=20)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Sucursal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('comentario', models.TextField(null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Sucursal')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Vendedor')),
            ],
        ),
    ]
