# Generated by Django 2.1.2 on 2018-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='encargado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
