# Generated by Django 2.1.2 on 2018-12-06 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20181205_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('Estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='Costo_p',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='producto',
            name='Costo_real',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Nota',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.AddField(
            model_name='producto',
            name='Tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='Tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='Tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tienda'),
            preserve_default=False,
        ),
    ]
